//go:build ignore
// +build ignore

// TEMPORARY AUTOGENERATED FILE: easyjson bootstapping code to launch
// the actual generator.

package main

import (
	"fmt"
	"os"

	"github.com/coderyw/easyjson/gen"

	pkg "gitlab.jkluck.vip/casino/golang/ca-common-util/model/config"
)

func main() {
	g := gen.NewGenerator("mysql_easyjson.go")
	g.SetPkg("model", "github.com/coderyw/easyjson/boostrap_test/model")
	g.Add(pkg.EasyJSON_exporter_DbConfig(nil))
	g.Add(pkg.EasyJSON_exporter_DbConfigOther(nil))
	g.Add(pkg.EasyJSON_exporter_ShardingTable(nil))
	g.Add(pkg.EasyJSON_exporter_Snowflake(nil))
	g.Add(pkg.EasyJSON_exporter_SnowflakeGen(nil))
	if err := g.Run(os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
